from pydantic import BaseModel, RootModel
from typing import Optional, Any


class CandidateProfile(RootModel):
    root: dict[str, Any]


class RunRequest(BaseModel):
    session_id: str
    candidate: CandidateProfile
    target_level: str
    panel_mode: str


class AgentPosition(BaseModel):
    TechnicalInterviewer: str
    CultureFitAssessor: str
    SeniorityAssessor: str


class RawVerdict(BaseModel):
    majority_position: str
    positions: AgentPosition
    dissent: Optional[str] = None


class BiasSummary(BaseModel):
    """
    Summary metrics of detected cognitive biases during the session.
    - total_flags: The total number of biases identified across all panel agents.
    - high_severity_count: Count of critical biases that heavily compromise decision integrity.
    - medium_severity_count: Count of moderate biases (e.g. anchoring).
    - low_severity_count: Count of minor biases or subtle personal preferences.
    - most_biased_agent: Name of the agent who had the highest count of bias flags.
    - dominant_bias_types: List of bias types that occurred most frequently.
    - confidence_score: Overall confidence in the panel's objectivity, scaled 20 to 100.
    """
    total_flags: int
    high_severity_count: int
    medium_severity_count: int
    low_severity_count: int
    most_biased_agent: str
    dominant_bias_types: list[str]
    confidence_score: int


class DebiasedVerdict(BaseModel):
    position: str
    changed_from_raw: bool
    change_explanation: Optional[str] = None
    key_reasons_for: list[str] = []
    key_reasons_against: list[str] = []


class FinalRecommendation(BaseModel):
    decision: str
    confidence: int
    justification: list[str]


class FinalVerdict(BaseModel):
    """
    The final output generated by the synthesizer.
    - session_id: The unique identifier for this evaluation run.
    - raw_verdict: The initial, unmoderated hiring positions of the panel.
    - bias_summary: Scored statistics from the BiasAuditor.
    - debiased_verdict: The revised verdict after removing biased arguments.
    - final_recommendation: Consolidated hiring advice and confidence score.
    """
    session_id: str
    raw_verdict: RawVerdict
    bias_summary: BiasSummary
    debiased_verdict: DebiasedVerdict
    final_recommendation: FinalRecommendation


class BiasFlag(BaseModel):
    """
    A single occurrence of cognitive bias flagged by the auditor.
    - agent_name: The panel agent that exhibited the bias.
    - bias_type: The category of bias (e.g. pedigree_bias, halo_effect).
    - quote: The exact sentence or phrase containing the biased reasoning.
    - severity: HIGH, MEDIUM, or LOW severity of the bias.
    - explanation: Why this is considered a bias and how it affects judgment.
    - corrective_reframe: How the panelist should re-evaluate the candidate objectively.
    """
    agent_name: str
    bias_type: str
    quote: str
    severity: str
    explanation: str
    corrective_reframe: str


class RunResponse(BaseModel):
    session_id: str
    status: str


class SynthesizerOutput(BaseModel):
    raw_verdict: RawVerdict
    bias_summary: BiasSummary
    debiased_verdict: DebiasedVerdict
    final_recommendation: FinalRecommendation


VERDICT_SCALE = [
    "STRONG_HIRE", "HIRE", "LEAN_HIRE",
    "LEAN_NO_HIRE", "NO_HIRE", "STRONG_NO_HIRE",
]

BIAS_TYPES = [
    "pedigree_bias", "halo_effect", "horn_effect", "affinity_bias",
    "anchoring", "attribution_bias", "recency_bias", "in_group_favoritism",
]

SEVERITY_LEVELS = ["LOW", "MEDIUM", "HIGH"]

AGENT_NAMES = [
    "TechnicalInterviewer",
    "CultureFitAssessor",
    "SeniorityAssessor",
    "BiasAuditor",
    "VerdictSynthesizer",
]
